# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'AppGB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftLint'

end

  # Pods for AppGB

  #target 'AppGBTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'AppGBUITests' do
    # Pods for testing
  #end
